import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettierRecommended from 'eslint-plugin-prettier/recommended';

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  prettierRecommended,
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'dist/**',
      'build/**',
      'content/challenges/**', // Exclude submodule
      'public/sw.js',
      'public/workbox-*.js',
      'public/fallback-*.js',
      'next-env.d.ts', // Generated by Next.js
      'tailwind.config.*', // Tailwind config can use require
    ],
  },
  {
    rules: {
      'prettier/prettier': 'error',
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/triple-slash-reference': 'off', // Allow triple slash in Next.js files
      '@typescript-eslint/no-require-imports': 'off', // Allow require in config files
      // New opinionated rule from the react-hooks plugin (eslint-config-next 16).
      // Flags intentional fetch-on-mount / state-sync effects here; keep as a
      // warning rather than refactoring working data-fetching effects.
      'react-hooks/set-state-in-effect': 'warn',
      'react/jsx-curly-brace-presence': [
        'error',
        {
          props: 'never',
          children: 'never',
        },
      ],
      'react/self-closing-comp': 'error',
    },
  },
];

export default eslintConfig;
