import { FlatCompat } from '@eslint/eslintrc';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),
  ...compat.plugins('prettier'),
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'dist/**',
      'build/**',
      'content/challenges/**', // Exclude submodule
      'public/sw.js',
      'public/workbox-*.js',
      'public/fallback-*.js',
      'next-env.d.ts', // Generated by Next.js
      'tailwind.config.*', // Tailwind config can use require
    ],
  },
  {
    rules: {
      'prettier/prettier': 'error',
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/triple-slash-reference': 'off', // Allow triple slash in Next.js files
      '@typescript-eslint/no-require-imports': 'off', // Allow require in config files
      'react/jsx-curly-brace-presence': [
        'error',
        {
          props: 'never',
          children: 'never',
        },
      ],
      'react/self-closing-comp': 'error',
    },
  },
];

export default eslintConfig;
